services:
  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  celery_worker:
    build: .
    command: celery -A bookroad worker -l info
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis # worker도 redis에 직접 의존하므로 추가하는 것이 좋습니다.
    env_file:
      - ./.env

volumes:
  postgres_data:
