# Generated by Django 5.2.7 on 2025-10-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='raw_toc',
            field=models.TextField(blank=True, help_text='알라딘 API 원본 목차(파싱 전)'),
        ),
    ]
