# Generated by Django 5.2.7 on 2025-10-21 06:01

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),

        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='도서 제목', max_length=512)),
                ('author', models.CharField(help_text='저자 (대표)', max_length=256)),
                ('isbn', models.CharField(db_index=True, help_text='ISBN 13자리', max_length=13, unique=True)),
                ('summary', models.TextField(blank=True, help_text='도서 요약 정보')),
                ('subtitle', models.CharField(blank=True, help_text='부제', max_length=512)),
                ('publisher', models.CharField(blank=True, help_text='출판사', max_length=256)),
                ('publication_date', models.DateField(blank=True, help_text='출간일', null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='쪽수', null=True)),
                ('full_description', models.TextField(blank=True, help_text='책소개 (상세)')),
                ('publisher_description', models.TextField(blank=True, help_text='출판사 제공 책소개')),
                ('authors_json', models.JSONField(blank=True, help_text='저자 상세 정보 (JSON)', null=True)),
                ('toc_parsing_failed', models.BooleanField(default=False, help_text='목차 파싱 실패 여부')),
                ('summary_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='요약 정보 임베딩 벡터', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='챕터 순서')),
                ('level', models.PositiveIntegerField(default=1, help_text='챕터 계층 레벨')),
                ('title', models.CharField(help_text='챕터 제목', max_length=1024)),
                ('title_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='챕터 제목 임베딩 벡터', null=True)),
                ('book', models.ForeignKey(help_text='연관 도서', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
