# Generated by Django 5.2.7 on 2025-10-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_raw_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(help_text='챕터 제목'),
        ),
    ]
